# Waring!
# This file is important for MayDOS Community Edition
# DO NOT EDIT THIS FILE unless you are the professional engineer

import os,sys

mdscversion = 'dev1.0'
sysroot = os.getcwd()
pypath = sys.executable